#!/usr/bin/env bash
# Installs nginx server on macOS using Homebrew

# Install nginx using Homebrew
brew update
brew install nginx

# Allow nginx to start at login and start it now
brew services start nginx

# Replace the default index.html with "Hello World!" message
echo "Hello World!" | sudo tee /usr/local/var/www/index.html

# Restart nginx to apply changes
brew services restart nginx
