#!/usr/bin/env bash
# Installs and configures nginx server on Ubuntu

# Update package list and install nginx
apt-get update
apt-get -y install nginx

# Allow 'Nginx HTTP' through the firewall
ufw allow 'Nginx HTTP'

# Replace the default page with "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Restart nginx using service command
service nginx restart
